drop table cities if exists;
drop table housing if exists;

create table cities (id bigint generated by default as identity, name varchar(255) not null, state varchar(255) not null, primary key (id));
create table housing (apartment_size integer not null, data_date date, rent_cost numeric(10,2) not null, rent_per_sqm numeric(10,2), city_id bigint not null, id bigint generated by default as identity, primary key (id));
alter table housing add constraint FK_CITY_HOUSING foreign key (city_id) references cities;
